#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
# also install selinux-policy to ensure /etc/selinux/config is present for disabling selinux
- name: install libselinux-python (present)
  yum: pkg=libselinux-python,selinux-policy state=present

- name: disable selinux
  selinux: state=disabled



