#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
- name: install pip (present)
  yum: pkg=python-pip state=latest
  when: ansible_os_family == 'RedHat'
  
- name: upgrade pip (latest)
  pip: name=pip state=latest

- name: install setuptools (latest)
  pip: name=setuptools state=latest



