#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
- name: install rsync (latest)
  yum: pkg=rsync state=latest



