#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
- name: install rsync (present)
  yum: pkg=rsync state=present
  when: ansible_os_family == 'RedHat'
  
- name: install rsync (present)
  apt: pkg=rsync state=present
  when: ansible_os_family == 'Debian'



