#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
- name: install libselinux-python (latest)
  yum: pkg=libselinux-python state=latest

- name: disable selinux
  selinux: state=disabled
  
- name: install epel-release (latest)
  yum: pkg=epel-release state=latest
  
- name: install graphite (latest)
  yum: pkg=supervisor,graphite-web,python-carbon state=latest
  notify:
  - restart httpd
  - restart carbon-cache
  
- name: setup graphite.db
  shell: python /usr/lib/python2.6/site-packages/graphite/manage.py syncdb --noinput
  args:
    creates: /var/lib/graphite-web/graphite.db
    
- name: chown graphite.db
  file: path=/var/lib/graphite-web/graphite.db owner=apache group=apache
  
- name: enable UDP in /etc/carbon/carbon.conf
  lineinfile:
    dest=/etc/carbon/carbon.conf
    regexp='ENABLE_UDP_LISTENER = (.*)'
    line='ENABLE_UDP_LISTENER = True'
    backrefs=yes
  notify:
  - restart carbon-cache

- name: start httpd and enable it at boot
  service: name=httpd state=started enabled=yes
  
- name: start carbon-cache and enable it at boot
  service: name=carbon-cache state=started enabled=yes

