#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
- hosts: all

  vars:
    http_port: 80
    max_clients: 200

  remote_user: root

  tasks:
  - name: install libselinux-python (latest)
    yum: pkg=libselinux-python state=latest
  
  - name: disable selinux
    selinux: state=disabled
    
  - name: install epel-release (latest)
    yum: pkg=epel-release state=latest
    
  - name: install graphite (latest)
    yum: pkg=supervisor,graphite-web,python-carbon state=latest
    notify:
    - restart httpd
    
  - name: setup graphite.db
    shell: python /usr/lib/python2.6/site-packages/graphite/manage.py syncdb --noinput
    args:
      creates: /var/lib/graphite-web/graphite.db
      
  - name: chown graphite.db
    file: path=/var/lib/graphite-web/graphite.db owner=apache group=apache

  handlers:
  # restart httpd (and enable it at boot)
  - name: restart httpd
    service: name=httpd state=restarted enabled=yes

