#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

---
# install fluentd
- name: check td.repo
  stat: path=/etc/yum.repos.d/td.repo
  register: td_repo

- name: install curl (present)
  yum: pkg=curl state=present
  when: td_repo.stat.exists == False

#- name: download installer shell script
#  get_url: url=https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh dest=/tmp/install-redhat-td-agent2.sh mode=755
#  when: td_repo.stat.exists == False

# this script: install-redhat-td-agent2.sh is executed via sudo, set [ssh_connection] pipelining = false in ansible.cfg
- name: install td-agent
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh | sh
  when: td_repo.stat.exists == False
  
# install fluent-plugin-elasticsearch
- name: check fluent-plugin-elasticsearch
  shell: /usr/sbin/td-agent-gem search --local fluent-plugin-elasticsearch
  register: check_plugin_elasticsearch

- name: install fluent-plugin-elasticsearch
  shell: /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch
  when: check_plugin_elasticsearch.stdout.find('fluent-plugin-elasticsearch') == -1

- name: start fluentd and enable it at boot
  service: name=td-agent state=started enabled=yes
