#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

---
# redhat | install collectd  
- include: ./install_collectd.redhat.yml
  when: ansible_os_family == 'RedHat'

# debian | install collectd  
- include: ./install_collectd.debian.yml
  when: ansible_os_family == 'Debian'
