#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
- hosts: all
  # accelerate: true

  vars:
    graphite_host: "new.graphite.host"
    graphite_port: "20030"
    graphite_protocol: "udp"
    graphite_prefix: "prefix-"
    graphite_postfix: "-postfix"

  remote_user: root

  tasks:
  - name: install rsync
    yum: pkg=rsync state=latest
  
  - name: copy rpms
    synchronize: src=./tmp/rpms dest=/tmp/ delete=yes
    
  - name: install collectd
    yum: pkg=/tmp/rpms/collectd-5.5.0-1.el6.x86_64.rpm,/tmp/rpms/collectd-base-config-1.0.0-1000.el6.noarch.rpm
    
  - name: setup collectd
    replace:
      dest=/etc/collectd.d/write_graphite.conf
      regexp='{{ item.regexp }}'
      replace='{{ item.replace }}'
      backup=no
    with_items:
    - { regexp: '(\s+Host\s+)"(.*)"', replace: '\1"{{ graphite_host }}"' }
    - { regexp: '(\s+Port\s+)"(.*)"', replace: '\1"{{ graphite_port }}"' }
    - { regexp: '(\s+Protocol\s+)"(.*)"', replace: '\1"{{ graphite_protocol }}"' }
    - { regexp: '(\s+Prefix\s+)"(.*)"', replace: '\1"{{ graphite_prefix }}"' }
    - { regexp: '(\s+Postfix\s+)"(.*)"', replace: '\1"{{ graphite_postfix }}"' }

