#!/usr/bin/ansible-playbook
# http://docs.ansible.com/ansible/modules_by_category.html

# requirements:
# yum install -y ansible (deploy)
# yum install -y libselinux-python (target)
---
- hosts: monitor-db
  roles:
  - graphite
  - graphite-beacon

- hosts: monitor-targets
  roles:
  - collectd
  - fluentd
  

